# Generated by Django 5.2.17 on 2026-08-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_patient_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientfollowup",
            name="dbp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientfollowup",
            name="sbp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
